FROM node:22-alpine

RUN apk add --no-cache \
    git \
    bash \
    coreutils \
    findutils \
    openssh-client \
    ca-certificates \
    curl \
 && git config --system --add safe.directory '*'
