// Package sshdefaults holds the shared SSH constants and the ssh config block
// builder used by setup-ssh and the printed SSH instructions.
package sshdefaults

import (
	"fmt"
	"strings"

	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain/types"
)

const (
	User        = "devuser"
	ServiceName = "devcontainer-ssh"
	Alias       = "devcontainer"
	KeyName     = types.SSHKeyName
	// RemoteKnownHostsPath is the known_hosts file referenced by a ProxyCommand
	// block pasted on the machine you connect FROM. That machine has its own
	// home, so — like the key — the path must use the ~ form rather than this
	// host's managed path.
	RemoteKnownHostsPath = "~/.ssh/devcontainer_known_hosts"
	// DockerIPFormat emits one IP per line so a container on several networks
	// does not concatenate addresses with no separator.
	DockerIPFormat = `{{range .NetworkSettings.Networks}}{{.IPAddress}}{{"\n"}}{{end}}`
	// ManagedMarker tags ~/.ssh/config Host blocks generated by this CLI. It is
	// emitted as a comment above the Host stanza (see ManagedComment) so destroy
	// and clean-ssh can locate and remove the right block by its target.
	ManagedMarker = "devcontainer-cli:managed"
	// MarkerVersion is stamped into the marker comment (v=<n>) so the format can
	// evolve without breaking older parsers; bump it on a breaking change.
	MarkerVersion = "1"
)

// Kind identifies what a managed SSH block targets, which decides how clean-ssh
// checks whether the target still exists. The type — not a comment — enumerates
// the valid values.
type Kind string

const (
	// KindWorkspace: the block belongs to a project workspace; ref is the (unique)
	// workspace name.
	KindWorkspace Kind = "workspace"
	// KindContainer: the block targets a specific container by name (loose
	// --container mode); ref is the container name.
	KindContainer Kind = "container"
)

// ManagedComment renders the structured marker comment that precedes a managed
// Host block, recording its kind, stable ref, and alias so destroy/clean-ssh can
// match it: e.g. "# devcontainer-cli:managed v=1 kind=workspace ref=myproj alias=myproj".
func ManagedComment(kind Kind, ref, alias string) string {
	return fmt.Sprintf("# %s v=%s kind=%s ref=%s alias=%s", ManagedMarker, MarkerVersion, kind, ref, alias)
}

// AuthorizedKeysInstallScript returns the sh script that installs a public key
// (piped on stdin) into the exec user's ~/.ssh/authorized_keys. It resolves the
// home from the container's live /etc/passwd instead of trusting ~/$HOME:
// docker exec delivers a stale HOME=/ when the entrypoint renumbered devuser's
// UID at runtime (the workspace-owner remap), which turned ~/.ssh into //.ssh.
func AuthorizedKeysInstallScript() string {
	return `H="$(getent passwd "$(id -u)" 2>/dev/null | cut -d: -f6)"; ` +
		`[ -d "$H" ] || H="$HOME"; { [ -n "$H" ] && [ "$H" != "/" ]; } || H=` + types.DevUserHome + `; ` +
		`mkdir -p "$H/.ssh" && cat >> "$H/.ssh/authorized_keys" && ` +
		`sort -u "$H/.ssh/authorized_keys" -o "$H/.ssh/authorized_keys" && ` +
		`chmod 700 "$H/.ssh" && chmod 600 "$H/.ssh/authorized_keys"`
}

// RemoteExportOptions carries everything RemoteExportScript embeds into the
// self-contained snippet pasted on the connecting machine. The key material is
// passed in as bytes (no I/O in this package); the caller reads the managed key.
type RemoteExportOptions struct {
	// PrivateKey is the raw private key written to ~/.ssh/<KeyName> (chmod 600).
	PrivateKey []byte
	// PublicKey is the raw public key written to ~/.ssh/<KeyName>.pub (chmod 644).
	PublicKey []byte
	// ConfigBlock is the rendered ~/.ssh/config Host stanza (from BuildConfigBlock)
	// appended to the connecting machine's ~/.ssh/config.
	ConfigBlock string
}

// RemoteExportScript renders one self-contained `sh` snippet for the connecting
// machine. It creates ~/.ssh (0700), writes the shared private key to
// ~/.ssh/<KeyName> (chmod 600) and the public key to ~/.ssh/<KeyName>.pub
// (chmod 644), then appends the ProxyCommand Host block to ~/.ssh/config. The
// key material and config block are embedded via quoted heredocs (no expansion),
// so this is a string-only renderer with no I/O; the snippet hands over a
// PRIVATE key and must be treated as sensitive.
func RemoteExportScript(opts RemoteExportOptions) string {
	keyPath := "~/.ssh/" + KeyName
	var b strings.Builder
	b.WriteString("mkdir -p ~/.ssh && chmod 700 ~/.ssh\n")
	b.WriteString(heredoc("> "+keyPath, "DC_KEY", string(opts.PrivateKey)))
	fmt.Fprintf(&b, "chmod 600 %s\n", keyPath)
	b.WriteString(heredoc("> "+keyPath+".pub", "DC_PUB", string(opts.PublicKey)))
	fmt.Fprintf(&b, "chmod 644 %s.pub\n", keyPath)
	b.WriteString(heredoc(">> ~/.ssh/config", "DC_CFG", "\n"+opts.ConfigBlock))
	return strings.TrimRight(b.String(), "\n")
}

// heredoc renders a `cat <redirect> <<'TAG' … TAG` block with body written
// verbatim (the quoted tag disables shell expansion). A trailing newline is
// ensured so the closing tag sits on its own line.
func heredoc(redirect, tag, body string) string {
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	return fmt.Sprintf("cat %s <<'%s'\n%s%s\n", redirect, tag, body, tag)
}

// Mode selects how the connecting machine reaches the container, which decides
// the ~/.ssh/config stanza BuildConfigBlock renders. The type — not a comment —
// enumerates the valid values.
type Mode string

const (
	// ModeLocal: the container is reachable by its IP from the same host running
	// the CLI (HostName = container IP).
	ModeLocal Mode = "local"
	// ModeRemote: the container lives on a remote docker host, reached via an ssh
	// hop to that host (ProxyCommand).
	ModeRemote Mode = "remote"
)

// ConfigBlockOptions carries everything BuildConfigBlock needs to render one
// ~/.ssh/config Host stanza. Which fields are required depends on Mode.
type ConfigBlockOptions struct {
	// Mode picks the stanza shape and therefore which fields below are consumed.
	Mode Mode
	// Alias is the connection name: the value after "Host " and what `ssh <alias>`
	// resolves to.
	Alias string
	// User is the login user inside the container (rendered as "User"; e.g. devuser).
	User string
	// KeyPath is the path to the private key, rendered as "IdentityFile".
	KeyPath string
	// Hostname is the target for "HostName": required in ModeLocal (the container
	// IP); unused in ModeRemote.
	Hostname string
	// Remote is the "USER@HOST" of the docker host used in the ProxyCommand ssh
	// hop; required in ModeRemote, unused otherwise.
	Remote string
	// Container is the container name inspected for its IP inside the ProxyCommand;
	// required in ModeRemote, unused otherwise.
	Container string
	// KnownHostsFile, when set, scopes host-key verification for this Host to that
	// file instead of ~/.ssh/known_hosts. A devcontainer regenerates its host keys
	// on every image rebuild while keeping the same container IP, so recording
	// them globally makes ssh report a changed host key ("REMOTE HOST
	// IDENTIFICATION HAS CHANGED") for what is really a fresh container. Keeping
	// them in a CLI-owned file lets the key be re-pinned from the docker daemon
	// (see SshService.PinContainerHostKeys) without ever rewriting the user's own
	// known_hosts. Left empty the stanza is emitted without host-key options.
	KnownHostsFile string
	// Kind and Ref, when both set, prepend a ManagedComment marker above the stanza
	// so destroy/clean-ssh can find and remove this block. Kind is the target type
	// (workspace/container) and Ref is its stable identity. Left empty the stanza is
	// emitted untagged.
	Kind Kind
	Ref  string
}

// BuildConfigBlock renders an ~/.ssh/config Host stanza for the given mode,
// prefixed with a managed marker comment when Kind and Ref are set.
func BuildConfigBlock(opts ConfigBlockOptions) (string, error) {
	stanza, err := buildStanza(opts)
	if err != nil {
		return "", err
	}
	if opts.Kind != "" && opts.Ref != "" {
		return ManagedComment(opts.Kind, opts.Ref, opts.Alias) + "\n" + stanza, nil
	}
	return stanza, nil
}

// ConfigOption is one `Keyword Value` line of an ssh config stanza, kept
// structured so callers can both render it and detect/refresh it in an already
// written block.
type ConfigOption struct {
	Keyword string
	Value   string
}

// Line renders the option as it appears inside a Host stanza (4-space indented).
func (o ConfigOption) Line() string { return "    " + o.Keyword + " " + o.Value }

// HostKeyOptions returns the host-key options that scope verification for a
// devcontainer Host to knownHostsFile: the file itself, accept-new so a
// first-seen container is trusted without a prompt, and unhashed entries so the
// CLI can find and replace a rebuilt container's key by hostname.
func HostKeyOptions(knownHostsFile string) []ConfigOption {
	return []ConfigOption{
		{Keyword: "UserKnownHostsFile", Value: knownHostsFile},
		{Keyword: "StrictHostKeyChecking", Value: "accept-new"},
		{Keyword: "HashKnownHosts", Value: "no"},
	}
}

// withHostKeyOptions appends the host-key options to stanza, or returns it
// unchanged when no known_hosts file was requested.
func withHostKeyOptions(stanza, knownHostsFile string) string {
	if knownHostsFile == "" {
		return stanza
	}
	var b strings.Builder
	b.WriteString(stanza)
	for _, opt := range HostKeyOptions(knownHostsFile) {
		b.WriteString("\n" + opt.Line())
	}
	return b.String()
}

// buildStanza renders the bare Host stanza for the given mode. Each case returns
// the whole stanza as one literal so it reads like the file it produces; defaults
// and validation are applied just before the Sprintf.
func buildStanza(opts ConfigBlockOptions) (string, error) {
	switch opts.Mode {
	case ModeLocal:
		if opts.Hostname == "" {
			return "", fmt.Errorf("hostname required for local mode")
		}
		stanza := fmt.Sprintf(`Host %s
    HostName %s
    User %s
    IdentityFile %s
    IdentitiesOnly yes`, opts.Alias, opts.Hostname, opts.User, opts.KeyPath)
		return withHostKeyOptions(stanza, opts.KnownHostsFile), nil

	case ModeRemote:
		if opts.Remote == "" {
			return "", fmt.Errorf("remote required for remote mode")
		}
		if opts.Container == "" {
			return "", fmt.Errorf("container required for remote mode")
		}
		// The ProxyCommand is wrapped in double quotes, so the command
		// substitution and the format's inner quotes must be escaped: \$ keeps the
		// docker inspect running on the remote host (not the local machine), and \"
		// stops the format's quotes from closing the ProxyCommand string. The IP
		// format itself carries Go-template-looking {{ }} braces, which is why this
		// stays plain Sprintf — feeding it through text/template would collide.
		escapedFormat := strings.ReplaceAll(DockerIPFormat, `"`, `\"`)
		ipExpr := fmt.Sprintf(`\$(docker inspect -f '%s' %s | head -n1)`, escapedFormat, opts.Container)
		stanza := fmt.Sprintf(`Host %s
    User %s
    IdentityFile %s
    IdentitiesOnly yes
    ProxyCommand ssh %s "nc -q0 %s 22"`, opts.Alias, opts.User, opts.KeyPath, opts.Remote, ipExpr)
		return withHostKeyOptions(stanza, opts.KnownHostsFile), nil
	}
	return "", fmt.Errorf("unknown mode %q", opts.Mode)
}
