export type ModuleOptionType = 'select' | 'multiselect' | 'input' | 'confirm';

// Directory inside the image where post-install scripts are baked, so they are
// available in any container (including remote-image `run`, which mounts no host files).
export const POST_SCRIPT_DIR = '/home/devuser/post-script';

export interface ModuleOptionChoice {
  value: string;
  label: string;
}

export interface ModuleOption {
  id: string;
  label: string;
  type: ModuleOptionType;
  choices?: ModuleOptionChoice[];
  default?: unknown;
  // Only prompt this option interactively when the given Dockerfile module is selected.
  requiresModule?: string;
}

export type DockerfileCategory = 'base' | 'infra' | 'lang' | 'runtime' | 'db' | 'cleanup';

export interface DockerfileModule {
  id: string;
  label: string;
  category: DockerfileCategory;
  always?: boolean;
  requires?: string[];
  conflicts?: string[];
  options?: ModuleOption[];
  copyFiles?: string[];
  postScriptFiles?: string[] | ((opts: Record<string, unknown>) => string[]);
  render(opts: Record<string, unknown>): string;
}

export interface RequiredEnvVar {
  name: string;
  prompt: string;
  default?: string;
}

export interface ComposeService {
  id: string;
  label: string;
  always?: boolean;
  // Only offer this service interactively when the given Dockerfile module is selected.
  requiresModule?: string;
  // Provisioned programmatically (e.g. from another option), never shown in the service picker.
  internal?: boolean;
  options?: ModuleOption[];
  requiresEnv?: RequiredEnvVar[];
  volumes?: string[];
  render(opts: ComposeRenderContext): Record<string, unknown>;
}

export interface ComposeRenderContext {
  imageName: string;
  enabledServiceIds: string[];
  options: Record<string, unknown>;
}

export interface SelectedModule {
  id: string;
  options?: Record<string, unknown>;
}

export type BuildMode = 'local-cached' | 'remote';
export const BUILD_MODES: readonly BuildMode[] = ['local-cached', 'remote'] as const;

export const REMOTE_VARIANTS = [
  'ssh',
  'nodejs',
  'bun',
  'java-temurin',
  'python',
  'go',
  'node-go',
  'node-python',
  'node-java-temurin',
  'bun-go',
  'bun-python',
  'bun-java-temurin',
] as const;
export type RemoteVariant = (typeof REMOTE_VARIANTS)[number];

export const VARIANT_LABELS: Record<RemoteVariant, string> = {
  ssh: 'ssh — full image (all modules)',
  nodejs: 'nodejs — Node.js only',
  bun: 'bun — Bun only',
  'java-temurin': 'java-temurin — Java Temurin only',
  python: 'python — Python only',
  go: 'go — Go only',
  'node-go': 'node-go — Node.js + Go',
  'node-python': 'node-python — Node.js + Python',
  'node-java-temurin': 'node-java-temurin — Node.js + Java Temurin',
  'bun-go': 'bun-go — Bun + Go',
  'bun-python': 'bun-python — Bun + Python',
  'bun-java-temurin': 'bun-java-temurin — Bun + Java Temurin',
};

export function parseVariant(v: string): RemoteVariant {
  if ((REMOTE_VARIANTS as readonly string[]).includes(v)) return v as RemoteVariant;
  throw new Error(`Invalid --variant: ${v}. Expected one of: ${REMOTE_VARIANTS.join(', ')}`);
}

export interface RemoteConfig {
  variant: RemoteVariant;
  registry?: string;
}

export interface DevcontainerConfig {
  mode: BuildMode;
  image: string;
  workspace: string;
  dockerfile: {
    modules: SelectedModule[];
  };
  compose: {
    services: (string | SelectedModule)[];
    subnet?: string;
  };
  env: Record<string, string>;
  remote?: RemoteConfig;
  fingerprint?: string;
}

export function normalizeServices(
  services: (string | SelectedModule)[],
): SelectedModule[] {
  return services.map((s) => (typeof s === 'string' ? { id: s, options: {} } : s));
}

export const CONFIG_FILE = 'devcontainer.config.json';
export const GENERATED_HEADER = '# AUTO-GENERATED by devcontainer CLI — edit devcontainer.config.json, not this file.';
