package types

// ContextSection is one module's or compose service's contribution to the
// generated ~/CONTEXT.md — the orientation document an AI coding agent reads to
// learn what THIS container provides and how it is meant to be driven.
//
// Sections are rendered once, at BUILD time, from the module's resolved
// options: every value a section mentions (a selected option, the node version,
// the resolved database user, a published port) must already be substituted in.
// Nothing in the document is evaluated at runtime — the live inventory is the
// job of the `get-devcontainer-context` command instead.
type ContextSection struct {
	// Title is the section heading, written without the leading "## ".
	Title string
	// Body is the markdown rendered under the heading. Leading and trailing
	// blank lines are trimmed by the generator, so it can be written as a raw
	// backtick literal.
	Body string
}

// GeneratedContextHeader marks ~/CONTEXT.md as CLI-generated. It carries the
// same sentinel string as GeneratedHeader so assets.IsGeneratedFile recognises
// it, wrapped in an HTML comment so it stays invisible in rendered markdown.
const GeneratedContextHeader = `<!--
THIS WAS GENERATED BY DEVCONTAINER-CLI — IF YOU MODIFY IT MANUALLY, ANY CHANGES
WILL BE LOST WHEN REGENERATED. EDIT devcontainer.config.json INSTEAD.
-->`

// ContextFileName is the generated document's name, both in the build directory
// and in devuser's home inside the container.
const ContextFileName = "CONTEXT.md"
