package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

type ModuleOptionType string

const (
	ModuleOptionSelect      ModuleOptionType = "select"
	ModuleOptionMultiselect ModuleOptionType = "multiselect"
	ModuleOptionInput       ModuleOptionType = "input"
	ModuleOptionConfirm     ModuleOptionType = "confirm"
)

const PostScriptDir = "/home/devuser/post-script"

type ModuleOptionChoice struct {
	Value string `json:"value"`
	Label string `json:"label"`
}

type ModuleOption struct {
	ID             string               `json:"id"`
	Label          string               `json:"label"`
	Type           ModuleOptionType     `json:"type"`
	Choices        []ModuleOptionChoice `json:"choices,omitempty"`
	Default        any                  `json:"default,omitempty"`
	RequiresModule string               `json:"requiresModule,omitempty"`
}

type DockerfileCategory string

const (
	CategoryBase    DockerfileCategory = "base"
	CategoryInfra   DockerfileCategory = "infra"
	CategoryLang    DockerfileCategory = "lang"
	CategoryRuntime DockerfileCategory = "runtime"
	CategoryDB      DockerfileCategory = "db"
	CategoryCleanup DockerfileCategory = "cleanup"
)

type RequiredEnvVar struct {
	Name    string `json:"name"`
	Prompt  string `json:"prompt"`
	Default string `json:"default,omitempty"`
}

type SelectedModule struct {
	ID      string         `json:"id"`
	Options map[string]any `json:"options,omitempty"`
}

type BuildMode string

const (
	BuildModeLocalCached BuildMode = "local-cached"
	BuildModeRemote      BuildMode = "remote"
)

var BuildModes = []BuildMode{BuildModeLocalCached, BuildModeRemote}

var RemoteVariants = []string{
	"ssh",
	"nodejs",
	"bun",
	"java-temurin",
	"python",
	"go",
	"node-go",
	"node-python",
	"node-java-temurin",
	"bun-go",
	"bun-python",
	"bun-java-temurin",
}

var VariantLabels = map[string]string{
	"ssh":               "ssh — full image (all modules)",
	"nodejs":            "nodejs — Node.js only",
	"bun":               "bun — Bun only",
	"java-temurin":      "java-temurin — Java Temurin only",
	"python":            "python — Python only",
	"go":                "go — Go only",
	"node-go":           "node-go — Node.js + Go",
	"node-python":       "node-python — Node.js + Python",
	"node-java-temurin": "node-java-temurin — Node.js + Java Temurin",
	"bun-go":            "bun-go — Bun + Go",
	"bun-python":        "bun-python — Bun + Python",
	"bun-java-temurin":  "bun-java-temurin — Bun + Java Temurin",
}

func ParseVariant(v string) (string, error) {
	for _, rv := range RemoteVariants {
		if rv == v {
			return v, nil
		}
	}
	return "", fmt.Errorf("invalid --variant: %s. Expected one of: %s", v, strings.Join(RemoteVariants, ", "))
}

type RemoteConfig struct {
	Variant  string `json:"variant"`
	Registry string `json:"registry,omitempty"`
}

type DockerfileConfig struct {
	Modules []SelectedModule `json:"modules"`
}

type ComposeConfig struct {
	Services []any  `json:"services"`
	Subnet   string `json:"subnet,omitempty"`
}

type DevcontainerConfig struct {
	Mode        BuildMode         `json:"mode"`
	Image       string            `json:"image"`
	Workspace   string            `json:"workspace"`
	Dockerfile  DockerfileConfig  `json:"dockerfile"`
	Compose     ComposeConfig     `json:"compose"`
	Env         map[string]string `json:"env"`
	Remote      *RemoteConfig     `json:"remote,omitempty"`
	Fingerprint string            `json:"fingerprint,omitempty"`
}

const ConfigFile = "devcontainer.config.json"
const GeneratedHeader = "# AUTO-GENERATED by devcontainer CLI — edit devcontainer.config.json, not this file."

func NormalizeServices(services []any) []SelectedModule {
	result := make([]SelectedModule, 0, len(services))
	for _, s := range services {
		switch v := s.(type) {
		case string:
			result = append(result, SelectedModule{ID: v, Options: map[string]any{}})
		case map[string]any:
			raw, err := json.Marshal(v)
			if err != nil {
				continue
			}
			var sm SelectedModule
			if err := json.Unmarshal(raw, &sm); err != nil {
				continue
			}
			if sm.Options == nil {
				sm.Options = map[string]any{}
			}
			result = append(result, sm)
		case SelectedModule:
			if v.Options == nil {
				v.Options = map[string]any{}
			}
			result = append(result, v)
		}
	}
	return result
}
