package dockerfile

import (
	"fmt"

	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain/types"
)

// BakedAliasFile is the image-baked default alias/function file, sourced from
// every rc file. It is owned by the CLI and rewritten on every build.
const BakedAliasFile = ".devcontainer_aliases.sh"

// UserAliasFile is the user's own alias file inside the container. The
// entrypoint symlinks it into the shared-config volume (types.SharedConfigEntries)
// so it persists across every container; its contents come from the CLI config
// (`config alias set`), pushed into the volume with `config alias sync`. It is
// sourced AFTER BakedAliasFile so user definitions win.
const UserAliasFile = ".alias.sh"

// ContextScriptName is the introspection command installed on PATH.
const ContextScriptName = "get-devcontainer-context"

// AliasesModule installs the CLI's default shell aliases/functions (kill_port,
// npm→pnpm, pip→uv, the `<tool>_yolo` agent launchers), the ~/CONTEXT.md
// orientation document and the get-devcontainer-context introspection command.
//
// It is Always-on and sits in CategoryBase directly after BaseModule: the zsh
// installer inside BaseModule rewrites ~/.zshrc from scratch, so anything that
// appends to the rc files must run after it. It takes no options: the agent
// aliases are unconditional (each guarded by `command -v` inside alias.sh), so
// the shipped script is never templated and the build is identical everywhere.
var AliasesModule = &ModuleSpec{
	ID:       types.ModuleAliases,
	Label:    "Aliases & container context (kill_port, npm→pnpm, pip→uv, ~/CONTEXT.md)",
	Category: types.CategoryBase,
	Always:   true,
	// CONTEXT.md is deliberately NOT listed here: CopyFiles names embedded
	// assets to materialize, and CONTEXT.md is generated per project by
	// domain.GenerateContext. The generate flow writes it into the build dir and
	// folds it into the fingerprint itself.
	CopyFiles: []string{"alias.sh", ContextScriptName + ".sh"},
	Context: func(opts map[string]any) *types.ContextSection {
		return &types.ContextSection{
			Title: "Aliases and shell helpers",
			Body: ctxBody(
				"`kill_port <port>` frees a port that is already taken",
				"(`kill -9` on whatever `lsof` reports listening on it).",
				"",
				"Each AI agent CLI also gets a `<tool>_yolo` alias — `claude_yolo`, `codex_yolo`,",
				"`copilot_yolo`, `agy_yolo` — that runs it with its interactive permission prompts",
				"skipped, since the container is the sandbox. The plain `claude`, `codex`,",
				"`copilot` and `agy` commands are left untouched: opting out is the default.",
				"",
				"Two alias files are sourced by every shell, in this order:",
				"",
				"- `~/"+BakedAliasFile+"` — the CLI's defaults, baked into the image.",
				"  Editing it inside the container is pointless; the change is lost on recreate.",
				"- `~/"+UserAliasFile+"` — **the user's own aliases**. These are managed on the host",
				"  with `devcontainer-cli config alias set/unset` (stored in the CLI config, not",
				"  in a file you edit here) and pushed to every container via the shared volume,",
				"  so they persist and need no rebuild. Sourced last, so they override the defaults.",
			),
		}
	},
	Render: func(opts map[string]any) string {
		return fmt.Sprintf(`##
## SHELL ALIASES & CONTAINER CONTEXT
##
# Default aliases/functions (kill_port, npm->pnpm, pip->uv, <tool>_yolo agents),
# the generated ~/%[4]s orientation document for AI agents and the
# get-devcontainer-context introspection command, in a single layer.
#
# %[4]s is GENERATED by the CLI from this project's modules and services (see
# domain.GenerateContext) and written into the build dir next to this Dockerfile,
# so it describes the image it is baked into.
COPY alias.sh %[1]s/%[2]s
COPY %[3]s.sh %[1]s/.local/bin/%[3]s
COPY %[4]s %[1]s/%[4]s
RUN chmod 0644 %[1]s/%[2]s %[1]s/%[4]s && \
    chmod 0755 %[1]s/.local/bin/%[3]s && \
    chown -R devuser:devuser %[1]s/%[2]s %[1]s/%[4]s %[1]s/.local
%[5]s
`,
			devuserHome, BakedAliasFile, ContextScriptName, types.ContextFileName,
			emitShellSources(
				shellSource{File: BakedAliasFile},
				// The user's own file is sourced last so it overrides the defaults,
				// and guarded because the entrypoint only creates it at runtime.
				shellSource{File: UserAliasFile, Guarded: true},
			),
		)
	},
}
