package dockerfile

import (
	"fmt"

	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain/types"
)

// BakedAliasFile is the image-baked default alias/function file, sourced from
// every rc file. It is owned by the CLI and rewritten on every build.
const BakedAliasFile = ".devcontainer_aliases.sh"

// UserAliasFile is the user's own alias file inside the container. The
// entrypoint symlinks it into the shared-config volume (types.SharedConfigEntries)
// so it persists across every container; its contents come from the CLI config
// (`config alias set`), pushed into the volume with `config alias sync`. It is
// sourced AFTER BakedAliasFile so user definitions win.
const UserAliasFile = ".alias.sh"

// ContextScriptName is the introspection command installed on PATH.
const ContextScriptName = "get-devcontainer-context"

// SkillsDir is the CLI-owned, image-baked store of agent skills, relative to
// devuser's home. It deliberately sits OUTSIDE the shared-config volume: the
// entrypoint only symlinks the skills from here into each agent's own skills
// directory, so every container always resolves the skill of the image it is
// actually running instead of persisting a stale copy in the volume.
const SkillsDir = ".devcontainer-skills"

// ContextSkillName is the global skill baked into every image: it tells an agent
// it is inside a devcontainer and to read ~/CONTEXT.md / run
// get-devcontainer-context before doing anything else.
const ContextSkillName = "devcontainer-context"

// ContextSkillAsset is the embedded markdown shipped as that skill's SKILL.md.
const ContextSkillAsset = "skill-" + ContextSkillName + ".md"

// AliasesModule installs the CLI's default shell aliases/functions (kill_port,
// npm→pnpm, pip→uv, the `<tool>_yolo` agent launchers), the ~/CONTEXT.md
// orientation document, the get-devcontainer-context introspection command and
// the always-installed `devcontainer-context` agent skill that points at both.
//
// It is Always-on and sits in CategoryBase directly after BaseModule: the zsh
// installer inside BaseModule rewrites ~/.zshrc from scratch, so anything that
// appends to the rc files must run after it. It takes no options: the agent
// aliases are unconditional (each guarded by `command -v` inside alias.sh), so
// the shipped script is never templated and the build is identical everywhere.
var AliasesModule = &ModuleSpec{
	ID:       types.ModuleAliases,
	Label:    "Aliases & container context (kill_port, npm→pnpm, pip→uv, ~/CONTEXT.md)",
	Category: types.CategoryBase,
	Always:   true,
	// CONTEXT.md is deliberately NOT listed here: CopyFiles names embedded
	// assets to materialize, and CONTEXT.md is generated per project by
	// domain.GenerateContext. The generate flow writes it into the build dir and
	// folds it into the fingerprint itself.
	CopyFiles: []string{"alias.sh", ContextScriptName + ".sh", ContextSkillAsset},
	Context: func(opts map[string]any) *types.ContextSection {
		return &types.ContextSection{
			Title: "Aliases and shell helpers",
			Body: ctxBody(
				"`kill_port <port>` frees a port that is already taken",
				"(`kill -9` on whatever `lsof` reports listening on it).",
				"",
				"Each AI agent CLI also gets a `<tool>_yolo` alias — `claude_yolo`, `codex_yolo`,",
				"`copilot_yolo`, `agy_yolo` — that runs it with its interactive permission prompts",
				"skipped, since the container is the sandbox. The plain `claude`, `codex`,",
				"`copilot` and `agy` commands are left untouched: opting out is the default.",
				"",
				"Two alias files are sourced by every shell, in this order:",
				"",
				"- `~/"+BakedAliasFile+"` — the CLI's defaults, baked into the image.",
				"  Editing it inside the container is pointless; the change is lost on recreate.",
				"- `~/"+UserAliasFile+"` — **the user's own aliases**. These are managed on the host",
				"  with `devcontainer-cli config alias set/unset` (stored in the CLI config, not",
				"  in a file you edit here) and pushed to every container via the shared volume,",
				"  so they persist and need no rebuild. Sourced last, so they override the defaults.",
				"",
				"A global agent skill named `"+ContextSkillName+"` is installed in every image",
				"(baked at `~/"+SkillsDir+"/"+ContextSkillName+"/SKILL.md`, linked into the agents'",
				"skills directories). It says what this file says: you are inside a container,",
				"read `~/CONTEXT.md` and run `"+ContextScriptName+"` before assuming anything",
				"about the environment.",
			),
		}
	},
	Render: func(opts map[string]any) string {
		return fmt.Sprintf(`##
## SHELL ALIASES & CONTAINER CONTEXT
##
# Default aliases/functions (kill_port, npm->pnpm, pip->uv, <tool>_yolo agents),
# the generated ~/%[4]s orientation document for AI agents, the
# get-devcontainer-context introspection command and the global
# "%[7]s" agent skill, in a single layer.
#
# %[4]s is GENERATED by the CLI from this project's modules and services (see
# domain.GenerateContext) and written into the build dir next to this Dockerfile,
# so it describes the image it is baked into.
#
# The skill is baked under %[1]s/%[6]s/, i.e. OUTSIDE the shared-config
# volume: the entrypoint symlinks it into each agent's own skills directory, so a
# container always sees the skill of the image it is actually running.
COPY alias.sh %[1]s/%[2]s
COPY %[3]s.sh %[1]s/.local/bin/%[3]s
COPY %[4]s %[1]s/%[4]s
COPY %[8]s %[1]s/%[6]s/%[7]s/SKILL.md
RUN chmod 0644 %[1]s/%[2]s %[1]s/%[4]s %[1]s/%[6]s/%[7]s/SKILL.md && \
    chmod 0755 %[1]s/.local/bin/%[3]s && \
    chown -R devuser:devuser %[1]s/%[2]s %[1]s/%[4]s %[1]s/.local %[1]s/%[6]s
%[5]s
`,
			devuserHome, BakedAliasFile, ContextScriptName, types.ContextFileName,
			emitShellSources(
				shellSource{File: BakedAliasFile},
				// The user's own file is sourced last so it overrides the defaults,
				// and guarded because the entrypoint only creates it at runtime.
				shellSource{File: UserAliasFile, Guarded: true},
			),
			SkillsDir, ContextSkillName, ContextSkillAsset,
		)
	},
}
