// Package assets embeds the helper shell scripts shipped with the CLI and
// materializes them into a project's build directory on demand. This replaces
// the Node SEA Asset API: in Go the embedded FS is always present, so there is
// no dev/disk fallback to maintain.
package assets

import (
	"embed"
	"os"
	"path/filepath"
	"strings"
)

//go:embed *.sh
var embedded embed.FS

const generatedMarker = "AUTO-GENERATED by devcontainer CLI"

type PreflightResult struct {
	Copied         []string
	AlreadyPresent []string
	Missing        []string
}

func chmodSafe(target string) {
	_ = os.Chmod(target, 0o755)
}

// AssetExists reports whether the named script is embedded in the binary.
func AssetExists(file string) bool {
	_, err := embedded.ReadFile(file)
	return err == nil
}

// Preflight materializes each required script into dir, skipping ones already
// present. A script that is neither present nor embedded is reported missing.
func Preflight(requiredFiles []string, dir string) PreflightResult {
	out := PreflightResult{}
	for _, f := range requiredFiles {
		target := filepath.Join(dir, f)
		if _, err := os.Stat(target); err == nil {
			out.AlreadyPresent = append(out.AlreadyPresent, f)
			continue
		}
		content, err := embedded.ReadFile(f)
		if err != nil {
			out.Missing = append(out.Missing, f)
			continue
		}
		if writeErr := os.WriteFile(target, content, 0o644); writeErr != nil {
			out.Missing = append(out.Missing, f)
			continue
		}
		chmodSafe(target)
		out.Copied = append(out.Copied, f)
	}
	return out
}

// ValidateRequiredFiles returns the subset of files that can be resolved
// neither from lookIn (when provided) nor from the embedded FS. An empty result
// means every reference is valid.
func ValidateRequiredFiles(files []string, lookIn string) []string {
	var missing []string
	for _, f := range files {
		if lookIn != "" {
			if _, err := os.Stat(filepath.Join(lookIn, f)); err == nil {
				continue
			}
		}
		if !AssetExists(f) {
			missing = append(missing, f)
		}
	}
	return missing
}

// IsGeneratedFile reports whether the file is absent or carries the CLI's
// auto-generated marker in its first 512 bytes.
func IsGeneratedFile(filePath string) bool {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return true
	}
	head := data
	if len(head) > 512 {
		head = head[:512]
	}
	return strings.Contains(string(head), generatedMarker)
}
