package assets_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/joacohbc/my-devcontainer-installer/cli/internal/infra/assets"
)

// entrypoint.sh is one of the scripts embedded via //go:embed *.sh.
const embeddedScript = "entrypoint.sh"

func TestAssetExists(t *testing.T) {
	if !assets.AssetExists(embeddedScript) {
		t.Errorf("expected %q to be embedded", embeddedScript)
	}
	if assets.AssetExists("definitely-not-real.sh") {
		t.Error("expected unknown asset to be reported missing")
	}
}

func TestPreflight_CopiesEmbeddedScript(t *testing.T) {
	dir := t.TempDir()
	res := assets.Preflight([]string{embeddedScript}, dir)
	if len(res.Copied) != 1 || res.Copied[0] != embeddedScript {
		t.Fatalf("expected %q copied, got %+v", embeddedScript, res)
	}
	if len(res.Missing) != 0 {
		t.Errorf("unexpected missing: %v", res.Missing)
	}
	if _, err := os.Stat(filepath.Join(dir, embeddedScript)); err != nil {
		t.Errorf("expected script materialized on disk: %v", err)
	}
}

func TestPreflight_AlreadyPresentIsSkipped(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, embeddedScript), []byte("custom"), 0o644); err != nil {
		t.Fatal(err)
	}
	res := assets.Preflight([]string{embeddedScript}, dir)
	if len(res.AlreadyPresent) != 1 {
		t.Fatalf("expected file reported already present, got %+v", res)
	}
	if len(res.Copied) != 0 {
		t.Errorf("should not overwrite an existing file, got copied %v", res.Copied)
	}
	got, _ := os.ReadFile(filepath.Join(dir, embeddedScript))
	if string(got) != "custom" {
		t.Errorf("existing file was overwritten: %q", got)
	}
}

func TestPreflight_MissingAsset(t *testing.T) {
	dir := t.TempDir()
	res := assets.Preflight([]string{"no-such-asset.sh"}, dir)
	if len(res.Missing) != 1 || res.Missing[0] != "no-such-asset.sh" {
		t.Errorf("expected missing asset reported, got %+v", res)
	}
}

func TestValidateRequiredFiles(t *testing.T) {
	if missing := assets.ValidateRequiredFiles([]string{embeddedScript}, ""); len(missing) != 0 {
		t.Errorf("embedded script should validate, got missing %v", missing)
	}
	if missing := assets.ValidateRequiredFiles([]string{"no-such-asset.sh"}, ""); len(missing) != 1 {
		t.Errorf("expected unknown asset reported missing, got %v", missing)
	}

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "local-only.sh"), []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if missing := assets.ValidateRequiredFiles([]string{"local-only.sh"}, dir); len(missing) != 0 {
		t.Errorf("file resolvable from lookIn should validate, got %v", missing)
	}
}

// entrypoint.sh must align devuser's UID/GID with the /workspace owner instead
// of rewriting ACLs on the bind mount, so the host's original permissions stay
// untouched.
func TestEntrypointAlignsUIDInsteadOfChangingWorkspaceACLs(t *testing.T) {
	body, err := os.ReadFile(embeddedScript)
	if err != nil {
		t.Fatalf("reading %s: %v", embeddedScript, err)
	}
	script := string(body)
	if !strings.Contains(script, "usermod -u") {
		t.Error("entrypoint must remap devuser's UID to the workspace owner (usermod -u)")
	}
	if strings.Contains(script, "setfacl -R") {
		t.Error("entrypoint must not run a recursive setfacl that mutates host permissions")
	}
}

func TestIsGeneratedFile(t *testing.T) {
	dir := t.TempDir()

	generated := filepath.Join(dir, "gen")
	if err := os.WriteFile(generated, []byte("# AUTO-GENERATED by devcontainer CLI\nFROM x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !assets.IsGeneratedFile(generated) {
		t.Error("expected file with marker to be reported generated")
	}

	handwritten := filepath.Join(dir, "hand")
	if err := os.WriteFile(handwritten, []byte("FROM ubuntu\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if assets.IsGeneratedFile(handwritten) {
		t.Error("expected unmarked file to be reported not generated")
	}

	if !assets.IsGeneratedFile(filepath.Join(dir, "does-not-exist")) {
		t.Error("expected absent file to be treated as generated (safe to overwrite)")
	}
}
