package domain_test

import (
	"strings"
	"testing"

	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain"
	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain/catalog"
	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain/types"
)

func mustGenerateContext(t *testing.T, config *types.DevcontainerConfig) string {
	t.Helper()
	out, err := domain.GenerateContext(config)
	if err != nil {
		t.Fatalf("GenerateContext: %v", err)
	}
	return out
}

// The document must carry the generated marker, so a user who edits it in the
// build dir does not have their edit silently preserved by IsGeneratedFile.
func TestGenerateContext_CarriesGeneratedMarker(t *testing.T) {
	out := mustGenerateContext(t, makeConfig())
	if !strings.Contains(out, "THIS WAS GENERATED BY DEVCONTAINER-CLI") {
		t.Errorf("CONTEXT.md must carry the generated marker:\n%s", out)
	}
	if !strings.HasPrefix(out, "<!--") {
		t.Errorf("the marker must be an HTML comment so it stays invisible when rendered:\n%s", out)
	}
}

// The preamble states where the project is mounted, and that path is derived
// from the workspace name rather than hardcoded.
func TestGenerateContext_PreambleUsesWorkspaceDir(t *testing.T) {
	config := makeConfig()
	config.Workspace = "myproj"
	out := mustGenerateContext(t, config)

	want := types.WorkspaceDir("myproj")
	if !strings.Contains(out, want) {
		t.Errorf("preamble must mention the resolved workspace dir %q:\n%s", want, out)
	}
	for _, frag := range []string{"inside a Docker container", "get-devcontainer-context", "no systemd"} {
		if !strings.Contains(out, frag) {
			t.Errorf("preamble must mention %q:\n%s", frag, out)
		}
	}
}

// A module that was not selected must not appear. This is the whole point of
// generating the document instead of shipping a static one.
func TestGenerateContext_OnlyIncludesSelectedModules(t *testing.T) {
	bare := mustGenerateContext(t, makeConfig())
	if strings.Contains(bare, "use `uv`") {
		t.Errorf("a config without python must not describe uv:\n%s", bare)
	}
	if strings.Contains(bare, "use `pnpm`") {
		t.Errorf("a config without pnpm must not describe pnpm:\n%s", bare)
	}

	config := makeConfig()
	config.Dockerfile.Modules = []types.SelectedModule{{ID: types.ModulePython}}
	withPython := mustGenerateContext(t, config)
	if !strings.Contains(withPython, "use `uv`") {
		t.Errorf("selecting python must describe uv:\n%s", withPython)
	}
	if strings.Contains(withPython, "use `pnpm`") {
		t.Errorf("selecting python must not describe pnpm:\n%s", withPython)
	}
}

// Always-on modules are present even in a minimal config, and the sections a
// container can never do without come first.
func TestGenerateContext_AlwaysOnModulesComeFirst(t *testing.T) {
	out := mustGenerateContext(t, makeConfig())

	base := strings.Index(out, "## Base image")
	aliases := strings.Index(out, "## Aliases and shell helpers")
	if base == -1 || aliases == -1 {
		t.Fatalf("base and aliases sections must always be present:\n%s", out)
	}
	if base > aliases {
		t.Errorf("base must precede aliases (catalog order), got base=%d aliases=%d", base, aliases)
	}
	if !strings.Contains(out, "kill_port") {
		t.Errorf("the aliases section must document kill_port:\n%s", out)
	}
}

// A module's section is rendered from its resolved options, so flipping an
// option changes the document — this is the "all the values at BUILD" contract.
func TestGenerateContext_SectionsReflectModuleOptions(t *testing.T) {
	config := makeConfig()
	config.Dockerfile.Modules = []types.SelectedModule{
		{ID: types.ModulePython, Options: map[string]any{"uv": false}},
	}
	out := mustGenerateContext(t, config)

	if strings.Contains(out, "use `uv`") {
		t.Errorf("python with uv=false must not tell the agent to use uv:\n%s", out)
	}
	if !strings.Contains(out, "was **not** selected") {
		t.Errorf("python with uv=false must say so explicitly:\n%s", out)
	}
}

// The aliases section always documents the permission-prompt-free agents (the
// gate is gone), and names agy alongside the others.
func TestGenerateContext_AliasSectionDocumentsAgents(t *testing.T) {
	out := mustGenerateContext(t, makeConfig())
	if !strings.Contains(out, "skip") || !strings.Contains(out, "permission prompts") {
		t.Errorf("the aliases section must mention the prompt-free agents:\n%s", out)
	}
	if !strings.Contains(out, "`agy`") {
		t.Errorf("the aliases section must name agy:\n%s", out)
	}
}

// Compose services contribute too, with the credentials they were actually
// rendered with, and they come after the modules.
func TestGenerateContext_IncludesSelectedServices(t *testing.T) {
	config := makeConfig()
	config.Compose.Services = []types.SelectedService{
		{ID: types.ServicePostgres, Options: map[string]any{"version": "18-alpine"}},
	}
	out := mustGenerateContext(t, config)

	user, password := domain.ResolveDBCredentials()
	for _, frag := range []string{
		"## PostgreSQL (sibling container)",
		"host `postgres`, port `5432`",
		"postgres:18-alpine",
		"`" + user + "`",
		"`" + password + "`",
	} {
		if !strings.Contains(out, frag) {
			t.Errorf("postgres section must contain %q:\n%s", frag, out)
		}
	}

	if strings.Contains(out, "## Redis (sibling container)") {
		t.Errorf("an unselected service must not appear:\n%s", out)
	}

	if modules, services := strings.Index(out, "## Base image"), strings.Index(out, "## PostgreSQL (sibling container)"); modules > services {
		t.Errorf("module sections must precede service sections (modules=%d services=%d)", modules, services)
	}
}

// The devcontainer service is always enabled, and what it reports about ports
// is the difference between an agent knowing its server is reachable or not.
func TestGenerateContext_DevcontainerPorts(t *testing.T) {
	none := mustGenerateContext(t, makeConfig())
	if !strings.Contains(none, "No ports are published") {
		t.Errorf("with no ports the document must say so:\n%s", none)
	}

	config := makeConfig()
	config.Compose.Ports = []string{"8080:80"}
	withPorts := mustGenerateContext(t, config)
	if !strings.Contains(withPorts, "8080") {
		t.Errorf("published ports must be listed:\n%s", withPorts)
	}
	if strings.Contains(withPorts, "No ports are published") {
		t.Errorf("with ports published the document must not claim otherwise:\n%s", withPorts)
	}
}

// Remote builds have no Dockerfile to COPY the document into; the prebuilt
// image ships the one it was built with.
func TestGenerateContext_RemoteModeIsEmpty(t *testing.T) {
	config := makeConfig()
	config.Mode = types.BuildModeRemote
	if out := mustGenerateContext(t, config); out != "" {
		t.Errorf("remote mode must generate no CONTEXT.md, got:\n%s", out)
	}
}

// A section with an empty body must be dropped rather than leaving a dangling
// heading — modules return nil/empty when their option set makes them silent.
func TestGenerateContext_NoEmptySections(t *testing.T) {
	config := makeConfig()
	config.Dockerfile.Modules = []types.SelectedModule{
		// "none" means no JDK is installed, so java has nothing to say.
		{ID: types.ModuleJavaTemurin, Options: map[string]any{"versions": []string{"none"}}},
	}
	out := mustGenerateContext(t, config)
	if strings.Contains(out, "## Java") {
		t.Errorf("a module with no installed content must not emit a section:\n%s", out)
	}

	for _, line := range strings.Split(out, "\n") {
		if !strings.HasPrefix(line, "## ") {
			continue
		}
		if strings.TrimSpace(strings.TrimPrefix(line, "## ")) == "" {
			t.Errorf("empty section heading in:\n%s", out)
		}
	}
}

// Every catalog entry that declares a Context must produce a usable section for
// its default options — a section with a title but no body would render as a
// dangling heading, and one with a body but no title cannot be placed.
func TestCatalogContextSectionsAreWellFormed(t *testing.T) {
	for _, m := range catalog.DockerfileModules {
		if m.Context == nil {
			continue
		}
		sec := m.Context(nil)
		if sec == nil {
			continue // legitimately silent for default options
		}
		if strings.TrimSpace(sec.Title) == "" {
			t.Errorf("module %q: context section has no title", m.ID)
		}
		if strings.TrimSpace(sec.Body) == "" {
			t.Errorf("module %q: context section has no body", m.ID)
		}
	}
}
