package domain_test

import (
	"strings"
	"testing"

	"github.com/goccy/go-yaml"
	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain"
	"github.com/joacohbc/my-devcontainer-installer/cli/internal/domain/types"
)

func makeConfig(overrides ...func(*types.DevcontainerConfig)) *types.DevcontainerConfig {
	cfg := &types.DevcontainerConfig{
		Mode:      types.BuildModeLocalCached,
		Image:     "devcontainer-ssh:local",
		Workspace: "devcontainer",
		Dockerfile: types.DockerfileConfig{
			Modules: []types.SelectedModule{},
		},
		Compose: types.ComposeConfig{
			Services: []any{},
			Subnet:   "172.25.0.0/24",
		},
		Env: map[string]string{},
	}
	for _, fn := range overrides {
		fn(cfg)
	}
	return cfg
}

func mustGenerateDockerfile(t *testing.T, cfg *types.DevcontainerConfig) string {
	t.Helper()
	out, err := domain.GenerateDockerfile(cfg)
	if err != nil {
		t.Fatalf("GenerateDockerfile failed: %v", err)
	}
	return out
}

func mustGenerateCompose(t *testing.T, cfg *types.DevcontainerConfig) string {
	t.Helper()
	out, err := domain.GenerateCompose(cfg)
	if err != nil {
		t.Fatalf("GenerateCompose failed: %v", err)
	}
	return out
}

func assertContainsStr(t *testing.T, haystack, needle, context string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("[%s] expected output to contain %q", context, needle)
	}
}

func assertNotContainsStr(t *testing.T, haystack, needle, context string) {
	t.Helper()
	if strings.Contains(haystack, needle) {
		t.Errorf("[%s] expected output NOT to contain %q", context, needle)
	}
}

func TestGenerateDockerfile_MinimalHasBaseAndCleanup(t *testing.T) {
	df := mustGenerateDockerfile(t, makeConfig())
	assertContainsStr(t, df, "FROM ubuntu:24.04", "minimal dockerfile")
	assertContainsStr(t, df, `ENTRYPOINT ["/entrypoint.sh"]`, "minimal dockerfile")
	assertContainsStr(t, df, "THIS WAS GENERATED BY DEVCONTAINER-CLI", "minimal dockerfile")
}

func TestGenerateDockerfile_AllSelectedModules(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{
			{ID: "java-temurin"},
			{ID: "python"},
			{ID: "sqlite"},
			{ID: "go"},
			{ID: "postgres-client"},
			{ID: "redis-client"},
			{ID: "mongo-client"},
			{ID: "nodejs"},
			{ID: "bun"},
			{ID: "tmux"},
			{ID: "php"},
			{ID: "rust"},
		}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "temurin-17-jdk", "full dockerfile")
	assertContainsStr(t, df, "python3-pip", "full dockerfile")
	assertContainsStr(t, df, "sqlite3", "full dockerfile")
	assertContainsStr(t, df, "install_golang", "full dockerfile")
	assertContainsStr(t, df, "postgresql-client", "full dockerfile")
	assertContainsStr(t, df, "redis-tools", "full dockerfile")
	assertContainsStr(t, df, "mongodb-mongosh", "full dockerfile")
	assertContainsStr(t, df, "nvm install --lts", "full dockerfile")
	assertContainsStr(t, df, "bun.sh/install", "full dockerfile")
	assertContainsStr(t, df, "tmux", "full dockerfile")
	assertContainsStr(t, df, "ppa:ondrej/php", "full dockerfile")
	assertContainsStr(t, df, "rustup.rs", "full dockerfile")
}

func TestGenerateDockerfile_TmuxModule(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "tmux"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "RUN apt-get update && apt-get install -y tmux && apt-get autoremove -y && apt-get autoclean && rm -rf /var/lib/apt/lists/*", "tmux")
}

func TestGenerateDockerfile_DodModule(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "dod"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "docker-ce-cli", "dod")
}

func TestGenerateDockerfile_PythonWithUvByDefault(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "python"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "astral.sh/uv/install.sh", "python default")
	assertContainsStr(t, df, ".python_init.sh", "python default")
	assertContainsStr(t, df, "for f in .zshrc .bashrc .profile", "python default")
}

func TestGenerateDockerfile_PythonWithoutUv(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{
			{ID: "python", Options: map[string]any{"uv": false}},
		}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertNotContainsStr(t, df, "astral.sh", "python no-uv")
}

func TestGenerateDockerfile_BunShellInit(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "bun"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "bun.sh/install", "bun")
	assertContainsStr(t, df, ".bun_init.sh", "bun")
	assertContainsStr(t, df, "for f in .zshrc .bashrc .profile", "bun")
}

func TestGenerateDockerfile_YarnAutoAddNodejs(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "yarn"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	// yarn requires nodejs, so the resolver must pull it in.
	assertContainsStr(t, df, "nvm install", "yarn pulls nodejs")
	// Yarn is provisioned through Corepack, sourcing the shared node init.
	assertContainsStr(t, df, "corepack prepare yarn@stable --activate", "yarn")
	assertContainsStr(t, df, ".nodejs_init.sh", "yarn sources node init")
}

func TestGenerateDockerfile_PnpmAutoAddNodejs(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "pnpm"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "nvm install", "pnpm pulls nodejs")
	assertContainsStr(t, df, "get.pnpm.io/install.sh", "pnpm")
	// pnpm must expose its global bin dir on PATH (zsh/bash/profile) and pin a
	// store-dir on the persisted home so no stray store lands in the workspace.
	assertContainsStr(t, df, "PNPM_HOME", "pnpm exports PNPM_HOME")
	assertContainsStr(t, df, ".pnpm_init.sh", "pnpm uses emitShellInit")
	assertContainsStr(t, df, "store-dir", "pnpm pins a store-dir")
	// pnpm aborts every command (even `config set`) when its configured global
	// bin dir is not on PATH, and that dir has moved between pnpm releases
	// ($PNPM_HOME vs $PNPM_HOME/bin), so the build step must put both
	// candidates on PATH before invoking pnpm. The store-dir must go through
	// `pnpm config set --global` (pnpm >= 11 ignores a hand-written legacy rc).
	assertContainsStr(t, df, `export PATH="$PNPM_HOME/bin:$PNPM_HOME:$PATH" && pnpm config set store-dir`, "pnpm config runs with both bin dirs on PATH")
	// Runtime shells need the same dirs on PATH for `pnpm` to be found.
	assertContainsStr(t, df, `\$PNPM_HOME/bin:\$PNPM_HOME:\$PATH`, "pnpm exposes its bin dirs on PATH")
}

func TestGenerateDockerfile_NodejsFnmManager(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{
			{ID: "nodejs", Options: map[string]any{"manager": "fnm"}},
		}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "fnm.vercel.app/install", "fnm")
	assertContainsStr(t, df, "fnm install --lts", "fnm")
	assertNotContainsStr(t, df, "nvm-sh/nvm", "fnm")
}

func TestGenerateDockerfile_NodejsFnmSpecificVersion(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{
			{ID: "nodejs", Options: map[string]any{"manager": "fnm", "version": "22"}},
		}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "fnm install 22", "fnm version 22")
}

func TestGenerateDockerfile_RemoteModeReturnsEmpty(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Mode = types.BuildModeRemote
		c.Remote = &types.RemoteConfig{Variant: "python"}
	})
	out, err := domain.GenerateDockerfile(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if out != "" {
		t.Errorf("expected empty string for remote mode, got %q", out)
	}
}

func TestGenerateCompose_ValidYAMLWithExpectedServices(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{"mongo", "tunnel"}
		c.Compose.Subnet = "10.0.0.0/24"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v\n%s", err, yml)
	}
	if parsed["name"] != "devcontainer" {
		t.Errorf("expected name to be %q, got %q", "devcontainer", parsed["name"])
	}
	services := parsed["services"].(map[string]any)
	if services["devcontainer-ssh"] == nil {
		t.Error("expected devcontainer-ssh service")
	}
	if services["mongo"] == nil {
		t.Error("expected mongo service")
	}
	if services["tunnel"] == nil {
		t.Error("expected tunnel service")
	}
	if services["redis"] != nil {
		t.Error("expected redis to be absent")
	}
	if services["postgres"] != nil {
		t.Error("expected postgres to be absent")
	}
}

func TestGenerateCompose_Labels(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{"mongo"}
		c.Compose.Subnet = "172.25.0.0/24"
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "python"}}
	})

	// 1. Validate Dockerfile Labels
	df, err := domain.GenerateDockerfile(cfg)
	if err != nil {
		t.Fatalf("failed to generate Dockerfile: %v", err)
	}
	assertContainsStr(t, df, "LABEL dev.devcontainer-installer.managed=\"true\"", "dockerfile labels")
	assertContainsStr(t, df, "dev.devcontainer-installer.project=", "dockerfile labels")
	assertContainsStr(t, df, "dev.devcontainer-installer.version=", "dockerfile labels")

	// 2. Validate Compose Labels
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}

	services := parsed["services"].(map[string]any)
	sshSvc := services["devcontainer-ssh"].(map[string]any)
	sshLabels := sshSvc["labels"].(map[string]any)
	if sshLabels["dev.devcontainer-installer.managed"] != "true" {
		t.Errorf("expected managed label on service, got %v", sshLabels)
	}

	networks := parsed["networks"].(map[string]any)
	netDef := networks["devcontainer-network"].(map[string]any)
	netLabels := netDef["labels"].(map[string]any)
	if netLabels["dev.devcontainer-installer.managed"] != "true" {
		t.Errorf("expected managed label on network, got %v", netLabels)
	}

	volumes := parsed["volumes"].(map[string]any)
	volDef := volumes["devcontainer_mongo_data"].(map[string]any)
	volLabels := volDef["labels"].(map[string]any)
	if volLabels["dev.devcontainer-installer.managed"] != "true" {
		t.Errorf("expected managed label on volume, got %v", volLabels)
	}
}

func TestGenerateCompose_DependsOnEnabledDBOnly(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{"mongo"}
		c.Compose.Subnet = "172.25.0.0/24"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	dependsOn := devSvc["depends_on"]
	if dependsOn == nil {
		t.Fatal("expected depends_on to be set when mongo is enabled")
	}
	deps, ok := dependsOn.([]any)
	if !ok || len(deps) != 1 || deps[0] != "mongo" {
		t.Errorf("expected depends_on=[mongo], got %v", dependsOn)
	}
}

func TestGenerateCompose_NoDependsOnWithoutDB(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{}
		c.Compose.Subnet = "172.25.0.0/24"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	if devSvc["depends_on"] != nil {
		t.Errorf("expected no depends_on, got %v", devSvc["depends_on"])
	}
}

func TestGenerateCompose_StaticIPFromSubnet(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{}
		c.Compose.Subnet = "172.25.0.0/28"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	networks := devSvc["networks"].(map[string]any)
	networkName := "devcontainer-network"
	netEntry := networks[networkName].(map[string]any)
	ipv4 := netEntry["ipv4_address"].(string)
	if ipv4 != "${DEVCONTAINER_IP:-172.25.0.14}" {
		t.Errorf("expected ipv4_address=${DEVCONTAINER_IP:-172.25.0.14}, got %q", ipv4)
	}
}

func TestGenerateCompose_DevcontainerHasNoDockerAccess(t *testing.T) {
	cfg := makeConfig()
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	volumes, _ := devSvc["volumes"].([]any)
	for _, v := range volumes {
		if strings.Contains(v.(string), "docker.sock") {
			t.Error("docker.sock must never be mounted")
		}
	}
	if devSvc["environment"] != nil {
		t.Errorf("expected no environment on devcontainer, got %v", devSvc["environment"])
	}
}

func TestGenerateCompose_DevcontainerHasDockerAccessWithDodModule(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "dod"}}
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	volumes, _ := devSvc["volumes"].([]any)
	hasSocket := false
	for _, v := range volumes {
		if strings.Contains(v.(string), "docker.sock") {
			hasSocket = true
			if v.(string) != "/var/run/docker.sock:/var/run/docker.sock" {
				t.Errorf("expected socket mount '/var/run/docker.sock:/var/run/docker.sock', got %q", v)
			}
		}
	}
	if !hasSocket {
		t.Error("expected docker.sock to be mounted when dod module is enabled")
	}
}

func TestGenerateCompose_VolumesHaveWorkspacePrefix(t *testing.T) {
	cfg := makeConfig()
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	volumes := parsed["volumes"].(map[string]any)
	for k := range volumes {
		// The shared tool-config volume is intentionally daemon-level (shared by
		// every workspace), so it is not workspace-prefixed.
		if k == types.SharedConfigVolumeName {
			continue
		}
		if !strings.HasPrefix(k, "devcontainer_") {
			t.Errorf("volume %q should have workspace prefix 'devcontainer_'", k)
		}
	}
}

func devcontainerVolumes(t *testing.T, yml string) []string {
	t.Helper()
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v\n%s", err, yml)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	raw, _ := devSvc["volumes"].([]any)
	out := make([]string, len(raw))
	for i, v := range raw {
		out[i] = v.(string)
	}
	return out
}

func topLevelVolumes(t *testing.T, yml string) map[string]any {
	t.Helper()
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v\n%s", err, yml)
	}
	if parsed["volumes"] == nil {
		return map[string]any{}
	}
	return parsed["volumes"].(map[string]any)
}

func devcontainerPorts(t *testing.T, yml string) []string {
	t.Helper()
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v\n%s", err, yml)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	raw, _ := devSvc["ports"].([]any)
	out := make([]string, len(raw))
	for i, v := range raw {
		out[i] = v.(string)
	}
	return out
}

func TestGenerateCompose_NoPortsByDefault(t *testing.T) {
	yml := mustGenerateCompose(t, makeConfig())
	if ports := devcontainerPorts(t, yml); len(ports) != 0 {
		t.Errorf("expected no ports by default, got %v", ports)
	}
	assertNotContainsStr(t, yml, "ports:", "no ports key when unset")
}

func TestGenerateCompose_PortsBoundToLoopback(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Ports = []string{"8080:80", "5432:5432"}
	})
	yml := mustGenerateCompose(t, cfg)
	got := devcontainerPorts(t, yml)
	want := []string{"127.0.0.1:8080:80", "127.0.0.1:5432:5432"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("ports = %v, want %v", got, want)
	}
}

func TestGenerateCompose_PortsRespectExplicitIP(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Ports = []string{"0.0.0.0:8080:80", "9090:90"}
	})
	yml := mustGenerateCompose(t, cfg)
	got := devcontainerPorts(t, yml)
	want := []string{"0.0.0.0:8080:80", "127.0.0.1:9090:90"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("ports = %v, want %v", got, want)
	}
}

func TestGenerateCompose_PersistVolumesDefaultAll(t *testing.T) {
	// A nil PersistVolumes (legacy/unset) mounts all three persistence volumes.
	yml := mustGenerateCompose(t, makeConfig())
	vols := devcontainerVolumes(t, yml)
	for _, want := range []string{"../..:/workspaces/devcontainer", "devcontainer_etc:/etc", "devcontainer_root:/root", "devcontainer_home:/home"} {
		found := false
		for _, v := range vols {
			if v == want {
				found = true
			}
		}
		if !found {
			t.Errorf("expected devcontainer volume %q, got %v", want, vols)
		}
	}
	top := topLevelVolumes(t, yml)
	for _, v := range []string{"devcontainer_etc", "devcontainer_root", "devcontainer_home"} {
		if top[v] == nil {
			t.Errorf("expected top-level volume %q, got %v", v, top)
		}
	}
}

func TestGenerateCompose_PersistVolumesSubset(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.PersistVolumes = &[]string{"home"}
	})
	yml := mustGenerateCompose(t, cfg)
	vols := devcontainerVolumes(t, yml)
	assertContainsStr(t, strings.Join(vols, "\n"), "../..:/workspaces/devcontainer", "subset workspace")
	assertContainsStr(t, strings.Join(vols, "\n"), "devcontainer_home:/home", "subset home")
	assertNotContainsStr(t, strings.Join(vols, "\n"), "devcontainer_etc:/etc", "subset no etc")
	assertNotContainsStr(t, strings.Join(vols, "\n"), "devcontainer_root:/root", "subset no root")

	top := topLevelVolumes(t, yml)
	if top["devcontainer_home"] == nil {
		t.Errorf("expected top-level devcontainer_home, got %v", top)
	}
	if top["devcontainer_etc"] != nil || top["devcontainer_root"] != nil {
		t.Errorf("unselected persistence volumes must not be declared, got %v", top)
	}
}

func TestGenerateCompose_PersistVolumesNone(t *testing.T) {
	off := false
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.PersistVolumes = &[]string{}
		c.Compose.SharedConfig = &off // isolate persist behavior from the shared mount
	})
	yml := mustGenerateCompose(t, cfg)
	vols := devcontainerVolumes(t, yml)
	if len(vols) != 1 || vols[0] != "../..:/workspaces/devcontainer" {
		t.Errorf("expected only the workspace mount, got %v", vols)
	}
	top := topLevelVolumes(t, yml)
	for k := range top {
		if strings.HasPrefix(k, "devcontainer_") {
			t.Errorf("expected no persistence volumes declared, found %q", k)
		}
	}
}

func TestGenerateCompose_WorkspaceMountIsUniquePerProject(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) { c.Workspace = "myproj" })
	yml := mustGenerateCompose(t, cfg)
	vols := devcontainerVolumes(t, yml)
	if !contains(vols, "../..:/workspaces/myproj") {
		t.Errorf("expected project mount at /workspaces/myproj, got %v", vols)
	}
	assertNotContainsStr(t, strings.Join(vols, "\n"), "../..:/workspace\n", "no bare /workspace mount")
}

func TestGenerateCompose_SharedConfigDefaultOn(t *testing.T) {
	// A default config (nil SharedConfig) mounts the shared volume and declares
	// it external, unprefixed by the workspace.
	cfg := makeConfig(func(c *types.DevcontainerConfig) { c.Workspace = "myproj" })
	yml := mustGenerateCompose(t, cfg)

	vols := devcontainerVolumes(t, yml)
	if !contains(vols, "devcontainer-shared-config:/mnt/shared-config") {
		t.Errorf("expected shared-config mount in devcontainer volumes, got %v", vols)
	}

	top := topLevelVolumes(t, yml)
	decl, ok := top["devcontainer-shared-config"].(map[string]any)
	if !ok {
		t.Fatalf("expected top-level devcontainer-shared-config volume, got %v", top)
	}
	if decl["external"] != true {
		t.Errorf("shared-config volume must be external, got %v", decl)
	}
	// Must NOT be workspace-prefixed.
	assertNotContainsStr(t, yml, "myproj_devcontainer-shared-config", "shared volume not prefixed")
	assertNotContainsStr(t, yml, "myproj-shared-config", "shared volume not prefixed")
}

func TestGenerateCompose_SharedConfigDisabled(t *testing.T) {
	off := false
	cfg := makeConfig(func(c *types.DevcontainerConfig) { c.Compose.SharedConfig = &off })
	yml := mustGenerateCompose(t, cfg)

	vols := devcontainerVolumes(t, yml)
	if contains(vols, "devcontainer-shared-config:/mnt/shared-config") {
		t.Errorf("shared-config mount must be absent when disabled, got %v", vols)
	}
	if top := topLevelVolumes(t, yml); top["devcontainer-shared-config"] != nil {
		t.Errorf("shared-config volume must not be declared when disabled, got %v", top)
	}
}

func TestGenerateCompose_SharedConfigRemoteMode(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Mode = types.BuildModeRemote
		c.Remote = &types.RemoteConfig{Variant: "nodejs"}
	})
	yml := mustGenerateCompose(t, cfg)
	if !contains(devcontainerVolumes(t, yml), "devcontainer-shared-config:/mnt/shared-config") {
		t.Error("expected shared-config mount in remote mode too")
	}
}

func TestPlannedComposeNames_ExcludesSharedConfig(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) { c.Workspace = "myproj" })
	_, _, volumes, err := domain.PlannedComposeNames(cfg)
	if err != nil {
		t.Fatalf("PlannedComposeNames failed: %v", err)
	}
	if contains(volumes, types.SharedConfigVolumeName) {
		t.Errorf("planned volumes must not include the shared volume, got %v", volumes)
	}
}

func contains(haystack []string, needle string) bool {
	for _, h := range haystack {
		if h == needle {
			return true
		}
	}
	return false
}

func TestGenerateCompose_NetworkNamedAfterWorkspace(t *testing.T) {
	cfg := makeConfig()
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	networks := parsed["networks"].(map[string]any)
	if networks["devcontainer-network"] == nil {
		t.Error("expected devcontainer-network in networks")
	}
}

func TestGenerateCompose_DevcontainerHostnameIsWorkspace(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Workspace = "my-project"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	if devSvc["hostname"] != "my-project" {
		t.Errorf("expected devcontainer hostname %q, got %v", "my-project", devSvc["hostname"])
	}
}

func TestGenerateCompose_DBServicesHaveNoHostname(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{"postgres"}
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	pg := services["postgres"].(map[string]any)
	if _, ok := pg["hostname"]; ok {
		t.Errorf("did not expect hostname on db service, got %v", pg["hostname"])
	}
}

func TestGenerateCompose_RemoteModeOmitsBuild(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Mode = types.BuildModeRemote
		c.Image = "ghcr.io/joacohbc/devcontainer-node-java-temurin:latest"
		c.Remote = &types.RemoteConfig{Variant: "node-java-temurin"}
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	if devSvc["build"] != nil {
		t.Errorf("expected no build in remote mode, got %v", devSvc["build"])
	}
	if devSvc["image"] != "ghcr.io/joacohbc/devcontainer-node-java-temurin:latest" {
		t.Errorf("expected remote image, got %v", devSvc["image"])
	}
}

func TestGenerateCompose_RemoteModeWithDBService(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Mode = types.BuildModeRemote
		c.Image = "ghcr.io/joacohbc/devcontainer-nodejs:latest"
		c.Remote = &types.RemoteConfig{Variant: "nodejs"}
		c.Compose.Services = []any{"mongo"}
		c.Compose.Subnet = "172.25.0.0/24"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	if services["mongo"] == nil {
		t.Error("expected mongo service in remote mode with DB selected")
	}
}

func TestResolveRemoteImage_NodeJSVariant(t *testing.T) {
	got := domain.ResolveRemoteImage("nodejs", "ghcr.io/joacohbc/")
	want := "ghcr.io/joacohbc/devcontainer-nodejs:latest"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestResolveRemoteImage_NonNodeJSVariant(t *testing.T) {
	got := domain.ResolveRemoteImage("bun", "ghcr.io/joacohbc/")
	want := "ghcr.io/joacohbc/devcontainer-bun:latest"
	if got != want {
		t.Errorf("expected %q, got %q", want, got)
	}
}

func TestResolveRemoteImage_DefaultRegistry(t *testing.T) {
	got := domain.ResolveRemoteImage("python", "")
	if !strings.HasSuffix(got, "devcontainer-python:latest") {
		t.Errorf("expected suffix devcontainer-python:latest, got %q", got)
	}
}

func TestGenerateCompose_FingerprintUsedAsImageName(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Mode = types.BuildModeLocalCached
		c.Fingerprint = "abc123def4567890abc123def4567890"
		c.Image = "should-not-be-used:tag"
	})
	yml := mustGenerateCompose(t, cfg)
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(yml), &parsed); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	services := parsed["services"].(map[string]any)
	devSvc := services["devcontainer-ssh"].(map[string]any)
	if devSvc["image"] != "devcontainer-cli/abc123def456:latest" {
		t.Errorf("expected fingerprint image, got %v", devSvc["image"])
	}
	if devSvc["build"] != "." {
		t.Errorf("expected build='.' in local-cached mode, got %v", devSvc["build"])
	}
}

func TestGenerateEnv_IncludesEnvVars(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Env = map[string]string{"TUNNEL_TOKEN": "abc"}
		c.Compose.Services = []any{}
		c.Compose.Subnet = "10.0.0.0/8"
	})
	env := domain.GenerateEnv(cfg)
	assertContainsStr(t, env, "TUNNEL_TOKEN=abc", "env")
	assertContainsStr(t, env, "DOCKER_SUBNET=10.0.0.0/8", "env")
	assertContainsStr(t, env, "COMPOSE_PROJECT_NAME=devcontainer", "env project name")
}

func TestGenerateEnv_DerivesIPFromDockerSubnetOverride(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Env = map[string]string{"DOCKER_SUBNET": "172.26.0.0/24"}
		c.Compose.Services = []any{}
		c.Compose.Subnet = "172.25.0.0/28"
	})
	env := domain.GenerateEnv(cfg)
	assertContainsStr(t, env, "DOCKER_SUBNET=172.26.0.0/24", "env override")
	assertContainsStr(t, env, "DEVCONTAINER_IP=172.26.0.254", "env override ip")
	assertContainsStr(t, env, "COMPOSE_PROJECT_NAME=devcontainer", "env project name")
}

func TestGenerateEnv_WritesBothSubnetAndIP(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Compose.Services = []any{}
		c.Compose.Subnet = "172.25.0.0/28"
	})
	env := domain.GenerateEnv(cfg)
	assertContainsStr(t, env, "DOCKER_SUBNET=172.25.0.0/28", "env subnet")
	assertContainsStr(t, env, "DEVCONTAINER_IP=172.25.0.14", "env ip")
	assertContainsStr(t, env, "COMPOSE_PROJECT_NAME=devcontainer", "env project name")
}

func TestGenerateDockerfile_ClaudeCode(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "claude-code"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-claude-code.sh", "claude-code script")
	assertContainsStr(t, df, "/home/devuser/post-script/", "post-script dir")
}

func TestGenerateDockerfile_Opencode(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "opencode"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-opencode.sh", "opencode script")
}

func TestGenerateDockerfile_CodexCli(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "codex-cli"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-codex-cli.sh", "codex-cli script")
	// codex-cli requires nodejs
	assertContainsStr(t, df, "nvm install --lts", "codex-cli requires nodejs")
}

func TestGenerateDockerfile_AntigravityCli(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "antigravity-cli"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-antigravity.sh", "antigravity-cli script")
}

func TestGenerateDockerfile_CopilotCli(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "copilot-cli"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-copilot.sh", "copilot-cli script")
}

func TestGenerateDockerfile_Graphify(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "graphify"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-graphify.sh", "graphify script")
	// graphify requires python
	assertContainsStr(t, df, "python3", "graphify requires python")
}

func TestGenerateDockerfile_Caveman(t *testing.T) {
	cfg := makeConfig(func(c *types.DevcontainerConfig) {
		c.Dockerfile.Modules = []types.SelectedModule{{ID: "caveman"}}
	})
	df := mustGenerateDockerfile(t, cfg)
	assertContainsStr(t, df, "install-caveman.sh", "caveman script")
	// caveman requires nodejs
	assertContainsStr(t, df, "nvm install --lts", "caveman requires nodejs")
}
