import { stringify } from 'yaml';
import { composeServices, getComposeService } from './registry.js';
import { resolveDockerfileModules } from './resolver.js';
import {
  GENERATED_HEADER,
  GENERATED_HEADER_YAML,
  type DevcontainerConfig,
} from './types.js';

export function generateDockerfile(config: DevcontainerConfig): string {
  const resolved = resolveDockerfileModules(config.dockerfile.modules);
  const fragments = resolved.map((r) => r.module.render(r.options).trim());
  return `${GENERATED_HEADER}\n\n${fragments.join('\n\n')}\n`;
}

export function generateCompose(config: DevcontainerConfig): string {
  const enabled = new Set<string>(config.compose.services);
  for (const svc of composeServices) {
    if (svc.always) enabled.add(svc.id);
  }
  const enabledIds = [...enabled];

  const services: Record<string, unknown> = {};
  const volumes: Record<string, null> = {};

  for (const id of enabledIds) {
    const svc = getComposeService(id);
    if (!svc) throw new Error(`Unknown compose service: ${id}`);
    services[svc.id === 'devcontainer' ? 'devcontainer-ssh' : svc.id] = svc.render({
      imageName: config.image,
      enabledServiceIds: enabledIds,
      options: {},
    });
    for (const v of svc.volumes ?? []) volumes[v] = null;
  }

  for (const v of ['devcontainer_etc', 'devcontainer_root', 'devcontainer_home']) {
    volumes[v] = null;
  }

  const subnet = config.compose.subnet ?? '172.25.0.0/24';
  const doc: Record<string, unknown> = {
    services,
    networks: {
      'local-network': {
        driver: 'bridge',
        ipam: { config: [{ subnet: `\${DOCKER_SUBNET:-${subnet}}` }] },
      },
    },
    volumes,
  };

  return `${GENERATED_HEADER_YAML}\n${stringify(doc, { lineWidth: 0 })}`;
}

export function generateEnv(config: DevcontainerConfig): string {
  const lines: string[] = ['# Generated by devcontainer CLI'];
  for (const [k, v] of Object.entries(config.env)) {
    lines.push(`${k}=${v}`);
  }
  if (!('DOCKER_SUBNET' in config.env) && config.compose.subnet) {
    lines.push(`DOCKER_SUBNET=${config.compose.subnet}`);
  }
  return lines.join('\n') + '\n';
}

export function collectRequiredCopyFiles(config: DevcontainerConfig): string[] {
  const resolved = resolveDockerfileModules(config.dockerfile.modules);
  const files = new Set<string>();
  for (const r of resolved) {
    for (const f of r.module.copyFiles ?? []) files.add(f);
  }
  return [...files];
}

export function collectRequiredEnvVars(
  config: DevcontainerConfig,
): { name: string; prompt: string; default?: string }[] {
  const enabled = new Set<string>(config.compose.services);
  const out: { name: string; prompt: string; default?: string }[] = [];
  for (const id of enabled) {
    const svc = getComposeService(id);
    for (const e of svc?.requiresEnv ?? []) out.push(e);
  }
  return out;
}
