import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

function currentDir(): string {
  try {
    const metaUrl = (import.meta as { url?: string }).url;
    if (metaUrl) return path.dirname(fileURLToPath(metaUrl));
  } catch {
    // ignore
  }
  return path.dirname(process.execPath);
}
const __dirname = currentDir();

interface SeaModule {
  isSea(): boolean;
  getAsset(key: string, encoding: 'utf8'): string;
}

function loadSea(): SeaModule | null {
  try {
    // node:sea is built-in on Node ≥ 20.12. In dev runs isSea() will be false even if the module loads.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require('node:sea') as SeaModule;
  } catch {
    return null;
  }
}

function assetsDirOnDisk(): string {
  const execDir = path.dirname(process.execPath);
  const candidates = [
    path.resolve(execDir, 'assets'),
    path.resolve(__dirname, '../assets'),
    path.resolve(__dirname, '../../assets'),
    path.resolve(__dirname, '../../cli/assets'),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return candidates[0];
}

export interface PreflightResult {
  copied: string[];
  alreadyPresent: string[];
  missing: string[];
}

function chmodSafe(target: string): void {
  try {
    fs.chmodSync(target, 0o755);
  } catch {
    // ignore chmod errors on non-POSIX FS
  }
}

export function preflight(requiredFiles: string[], cwd: string = process.cwd()): PreflightResult {
  const out: PreflightResult = { copied: [], alreadyPresent: [], missing: [] };
  const sea = loadSea();
  const useSea = !!sea && sea.isSea();
  const diskAssets = useSea ? null : assetsDirOnDisk();

  for (const f of requiredFiles) {
    const target = path.join(cwd, f);
    if (fs.existsSync(target)) {
      out.alreadyPresent.push(f);
      continue;
    }

    if (useSea && sea) {
      try {
        const content = sea.getAsset(f, 'utf8');
        fs.writeFileSync(target, content);
        chmodSafe(target);
        out.copied.push(f);
        continue;
      } catch {
        out.missing.push(f);
        continue;
      }
    }

    const src = path.join(diskAssets!, f);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, target);
      chmodSafe(target);
      out.copied.push(f);
    } else {
      out.missing.push(f);
    }
  }
  return out;
}

export const GENERATED_MARKER = 'AUTO-GENERATED by devcontainer CLI';

export function isGeneratedFile(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return true;
  const head = fs.readFileSync(filePath, 'utf8').slice(0, 512);
  return head.includes(GENERATED_MARKER);
}
