export type ModuleOptionType = 'select' | 'multiselect' | 'input' | 'confirm';

export interface ModuleOptionChoice {
  value: string;
  label: string;
}

export interface ModuleOption {
  id: string;
  label: string;
  type: ModuleOptionType;
  choices?: ModuleOptionChoice[];
  default?: unknown;
}

export type DockerfileCategory = 'base' | 'infra' | 'lang' | 'runtime' | 'db' | 'cleanup';

export interface DockerfileModule {
  id: string;
  label: string;
  category: DockerfileCategory;
  always?: boolean;
  requires?: string[];
  conflicts?: string[];
  options?: ModuleOption[];
  copyFiles?: string[];
  render(opts: Record<string, unknown>): string;
}

export interface ComposeService {
  id: string;
  label: string;
  always?: boolean;
  requiresEnv?: { name: string; prompt: string; default?: string }[];
  volumes?: string[];
  render(opts: ComposeRenderContext): Record<string, unknown>;
}

export interface ComposeRenderContext {
  imageName: string;
  enabledServiceIds: string[];
  options: Record<string, unknown>;
}

export interface SelectedModule {
  id: string;
  options?: Record<string, unknown>;
}

export interface DevcontainerConfig {
  image: string;
  dockerfile: {
    modules: SelectedModule[];
  };
  compose: {
    services: string[];
    subnet?: string;
  };
  env: Record<string, string>;
}

export const CONFIG_FILE = 'devcontainer.config.json';
export const GENERATED_HEADER = '# AUTO-GENERATED by devcontainer CLI — edit devcontainer.config.json, not this file.';
export const GENERATED_HEADER_YAML = '# AUTO-GENERATED by devcontainer CLI — edit devcontainer.config.json, not this file.';
