export type ModuleOptionType = 'select' | 'multiselect' | 'input' | 'confirm';

export interface ModuleOptionChoice {
  value: string;
  label: string;
}

export interface ModuleOption {
  id: string;
  label: string;
  type: ModuleOptionType;
  choices?: ModuleOptionChoice[];
  default?: unknown;
}

export type DockerfileCategory = 'base' | 'infra' | 'lang' | 'runtime' | 'db' | 'cleanup';

export interface DockerfileModule {
  id: string;
  label: string;
  category: DockerfileCategory;
  always?: boolean;
  requires?: string[];
  conflicts?: string[];
  options?: ModuleOption[];
  copyFiles?: string[];
  postScriptFiles?: string[];
  render(opts: Record<string, unknown>): string;
}

export interface ComposeService {
  id: string;
  label: string;
  always?: boolean;
  options?: ModuleOption[];
  requiresEnv?: { name: string; prompt: string; default?: string }[];
  volumes?: string[];
  render(opts: ComposeRenderContext): Record<string, unknown>;
}

export interface ComposeRenderContext {
  imageName: string;
  enabledServiceIds: string[];
  options: Record<string, unknown>;
}

export interface SelectedModule {
  id: string;
  options?: Record<string, unknown>;
}

export type BuildMode = 'local-cached' | 'remote';
export const BUILD_MODES: readonly BuildMode[] = ['local-cached', 'remote'] as const;

export const REMOTE_VARIANTS = [
  'ssh',
  'nodejs',
  'bun',
  'java-temurin',
  'python',
  'go',
  'node-go',
  'node-python',
  'node-java-temurin',
  'bun-go',
  'bun-python',
  'bun-java-temurin',
] as const;
export type RemoteVariant = (typeof REMOTE_VARIANTS)[number];

export interface RemoteConfig {
  variant: RemoteVariant;
  registry?: string;
}

export interface DevcontainerConfig {
  mode: BuildMode;
  image: string;
  workspace: string;
  dockerfile: {
    modules: SelectedModule[];
  };
  compose: {
    services: (string | SelectedModule)[];
    subnet?: string;
  };
  env: Record<string, string>;
  remote?: RemoteConfig;
  fingerprint?: string;
}

export function normalizeServices(
  services: (string | SelectedModule)[],
): SelectedModule[] {
  return services.map((s) => (typeof s === 'string' ? { id: s, options: {} } : s));
}

export const CONFIG_FILE = 'devcontainer.config.json';
export const GENERATED_HEADER = '# AUTO-GENERATED by devcontainer CLI — edit devcontainer.config.json, not this file.';
export const GENERATED_HEADER_YAML = '# AUTO-GENERATED by devcontainer CLI — edit devcontainer.config.json, not this file.';
